### PR TITLE
Fix debug mode & others page

### PR DESCRIPTION
**Pull request by MoLow**

### CODE REVIEW

**Comment by gysmo38** [comment]
Thank you :)

**Comment by gysmo38** [comment]
I am not sure but I think the html part missing for enable or disable HA autodiscovery.
Can you add it in a new PR?

**Comment by MoLow** [comment]
@gysmo38 seems to work for me.what html part is missing?

**Comment by gysmo38** [comment]
@MoLow I do not find on web page a button to enable or disable HA autodiscovery. I foudn the option in config.h but do you add this option in a page?

**Comment by MoLow** [comment]
@gysmo38 it already exists under /others, so no need of adding. Maybe we should just add a button in the menu

**Comment by gysmo38** [comment]
@MoLow yes you right :)  I think, I will move it in advanced page :)

**Pull request merged**
