### PR TITLE
Issue #67 - Auto restart on WiFi drop

### PR DESCRIPTION
**Pull request by loadrunner42**
restarts the board after timeout when WiFi dropped or in captive ap mode. Changed password in AP mode to match login_password

### CODE REVIEW

**Comment by ghost** [comment]
What if login password is not set? it's optional.
DHCP failure needs to be handled otherwise it will require a hard power reset.

**Comment by loadrunner42** [comment]
In that case it defaults to no password. I think this makes more sense than the current solution to use the SSID as the password.

**Comment by loadrunner42** [comment]
Two issues that this solves are:

1) No longer requires a firmware flash when wifi is permanently lost as it will revert to AP mode after the timeout (Currently 5min). This also allows easy confirmation that it’s just a Wi-Fi issue when the connection is lost.

2) No longer need to power cycle the aircon to get it to re-connect after the Wi-Fi AP is reset or there is a power outage.

**Comment by gysmo38** [comment]
For me it look good. Thank you :)

**Pull request merged**
