### PR TITLE
use version from git

### PR DESCRIPTION
**Pull request by ggrandou**
This patch automates the version string in the firmware by using the most recent available git tag.

python script is automatically called by platformio upon build which appends a GIT_VERSION define to build flags.

version string is built from the output of `git describe --tags --always --dirty` command

Some version examples:
   - 2023.8 when built on a tag
   - 2023.8-9-g103391f when built later than a tag
   - 2023.8-9-g103391f-dirty when built on a dirty tree

GIT_VERSION is gracefully ignored when the build is not run inside a git repository or if git fails for whatever reason.

For safety I have kept the original code if GIT_VERSION is not defined, but it could make sense to have a generic "unknown" version string or similar.

It has been tested on a linux platform. It should work on windows as well, but it's untested.

### CODE REVIEW

**Review by pzbitskiy — APPROVED** [review]
I tried it and it works great

**Comment by ggrandou** [comment]
> I tried it and it works great

on linux or on windows ?

**Comment by pzbitskiy** [comment]
Linux.

**Comment by gysmo38** [comment]
Thank you for your PR

**Comment by ggrandou** [comment]
Hello,
@gysmo38 looks like you have forgotten to actually do the merge in your master branch ;)

**Pull request closed without merging**
