### PR TITLE
Implement (real) action state

### LINKED ISSUE #95: When in cool mode, the "action" (HVAC state) property is always "cooling" even when unit is idle
Setting the unit to the cool mode puts it into a permanent "cooling" stage instead of alternating between "cooling" and "idle", even when the compressor is actually idle. Is this how it's meant to be?

I saw in the code the line ``//rootInfo["operating"]       = currentStatus.operating;`` was commented out with [this commit](https://github.com/gysmo38/mitsubishi2MQTT/commit/79179b014b5e8e099ac1c1cba833297f714b6d79). Was this for any particular reason? Right now, the `action` property is just a duplicate of the `mode` property according to the code.

### PR DESCRIPTION
**Pull request by melyux**
I've (re-)added the action state to the `/state` topic. It uses the existing but unused `operating` boolean and the current mode to determine the correct action name. The existing "action" state was just a copy of the "mode" to make Home Assistant happy, but after this change will actually reflect whether the compressor/pump is working (in the cooling/heating states). I've tested it on my unit and it's working so far, but it's a cooling-only model. Should fix #95

### CODE REVIEW

**Comment by mamrai1** [comment]
@melyux please check pull request 102!! i think i does the same thing

**Comment by melyux** [comment]
@mamrai1 Great minds think alike! Do you want to go for my PR because it also fixes the dummy packet sending for the fan_only mode, the unnecessary result variable assignment, also works for auto, and doesn’t expose “operating” because “action” already has the same logic?

**Comment by mamrai1** [comment]
Yes of course... I will test it tomorrow

**Comment by mamrai1** [comment]
I had time tonight and checked it. works ok with both of my units and HA. Nice!

**Comment by gysmo38** [comment]
Thanks

**Pull request merged**
