### PR TITLE
platformio support

### PR DESCRIPTION
**Pull request by lesleypersyn**

### CODE REVIEW

**Comment by gysmo38** [comment]
I am not using platformio and don't plan to use it. But If you found this usefull and it break nothing, I accept this change :)

**Comment by jmvaz** [comment]
@gysmo38 you should give it a try. You will never return to arduino ide!

**Comment by gysmo38** [comment]
@jmvaz I already try, but I found it not easy to use. I use VSCode with arduino plugin. I will try it again.

**Comment by MoLow** [comment]
I use vscode as well and works great

**Pull request merged**
