### PR TITLE
Update mitsubishi2mqtt.ino

### PR DESCRIPTION
**Pull request by lesleypersyn**
fix for Temperature set in Home Assistant bounces to default value #106

### CODE REVIEW

**Comment by gysmo38** [comment]
Thanks :)

**Comment by melyux** [comment]
This was already fixed with #105, and this merge conflicts with that fix and messes things up again. This PR needs to be reversed @gysmo38.

Please check when merging multiple pending PRs because multiple people try to fix the same thing at the same time (happened last time too).

**Comment by gysmo38** [comment]
I reversed but not sure this is the good one.... Are you sure you are on the good PR?

**Comment by melyux** [comment]
Hmm not sure what you mean. Am I sure this is fixed by the other one? Yes. In fact, this PR as it is will convert your set temperature from Fahrenheit... into Fahrenheit, causing monstrous temperature settings like 169°F when you wanted 76°F.

**Comment by gysmo38** [comment]
@melyux ok thank you. I think it is ok now :)

**Comment by melyux** [comment]
@gysmo38 I think you may have closed your revert PR for some reason, unless I’m missing something. The code is still showing the results of this PR.

**Comment by melyux** [comment]
@gysmo38 This change still needs to be undone, the current code is in an incorrect state

**Comment by gysmo38** [comment]
@melyux if you can made a new PR to correct what is undone, it simplest for me.

**Comment by melyux** [comment]
@gysmo38 Done! #112

**Pull request merged**
